### ISSUE TITLE
Config

### ISSUE THREAD

**Issue by yamamoto-yuta** [RibbonCMS/FunctionalBlogTemplate-DEMO#1]
```yaml
blog_title: Functional Blog Template - DEMO
site_introduction: This is demo page of Functional Blog Template.
copylight_name: RibbonCMS team
copylight_url: https://ribboncms.github.io
root_url: https://ribboncms.github.io/FunctionalBlogTemplate-DEMO
issues_page_url: https://github.com/RibbonCMS/FunctionalBlogTemplate-DEMO/issues
favicon_image_url: https://github-production-user-asset-6210df.s3.amazonaws.com/55144709/260206505-4249b803-3da9-4d66-8ab1-bc07e58e1d3a.png
author_name: RibbonCMS team
author_introduction: We are RibbonCMS team.
avatar_image_url: https://github-production-user-asset-6210df.s3.amazonaws.com/55144709/260206505-4249b803-3da9-4d66-8ab1-bc07e58e1d3a.png
sns:
  - name: GitHub
    url: https://ribboncms.github.io/FunctionalBlogTemplate
#  - name: Twitter
#    url: 
#  - name: Facebook
#    url: 
#  - name: LinkedIn
#    url: 
#  - name: Instagram
#    url: 
#  - name: Youtube
#    url: 
```
