### ISSUE TITLE
Index

### ISSUE THREAD

**Issue by yamamoto-yuta** [RibbonCMS/FunctionalBlogTemplate-DEMO#2]
```yaml
site_description: |-
  # このページは何？
  RibbonCMS のフロントエンドテンプレート "FunctionalBlogTemplate" のリポジトリです。
site_header_title: "FunctionalBlogTemplate - DEMO"
```
