### ISSUE TITLE
Profile

### ISSUE THREAD

**Issue by yamamoto-yuta** [RibbonCMS/FunctionalBlogTemplate-DEMO#4]
```yaml
# Your skills
site_description: "RibbonCMS FunctionalBlogTemplate Profile"
author_description_detail: "We are RibbonCMS team!"
skills_data:
  - title: Python
    description: |-
      sideM の開発言語です。
    image_url: https://user-images.githubusercontent.com/42331656/168748967-d8aeac42-4035-425e-809a-3b7687f794a5.png
    tags:
      - sideM
  - title: Next.js
    description: |-
      このテンプレートで採用しています。
    image_url: https://user-images.githubusercontent.com/42331656/168748817-f8bff2cc-d444-436c-86b1-fec14ea98bab.png
    tags:
      - sideF

# Your works
works_data:
  - title: RibbonCMS
    description: |-
      - **Next.js／Python**製のコンテンツ管理システムです。GitHub Issuesの操作のみでブログや固定ページの投稿・更新ができることが特徴です。
    image_url: https://user-images.githubusercontent.com/42331656/168722759-38bce3a8-55fd-44d1-a992-9d2a73377087.png
    url: https://github.com/RibbonCMS
  - title: RibbonCMS
    description: |-
      - **Next.js／Python**製のコンテンツ管理システムです。GitHub Issuesの操作のみでブログや固定ページの投稿・更新ができることが特徴です。
    image_url: https://user-images.githubusercontent.com/42331656/168722759-38bce3a8-55fd-44d1-a992-9d2a73377087.png
    url: https://github.com/RibbonCMS
  - title: RibbonCMS
    description: |-
      - **Next.js／Python**製のコンテンツ管理システムです。GitHub Issuesの操作のみでブログや固定ページの投稿・更新ができることが特徴です。
    image_url: https://user-images.githubusercontent.com/42331656/168722759-38bce3a8-55fd-44d1-a992-9d2a73377087.png
    url: https://github.com/RibbonCMS
  - title: RibbonCMS
    description: |-
      - **Next.js／Python**製のコンテンツ管理システムです。GitHub Issuesの操作のみでブログや固定ページの投稿・更新ができることが特徴です。
    image_url: https://user-images.githubusercontent.com/42331656/168722759-38bce3a8-55fd-44d1-a992-9d2a73377087.png
    url: https://github.com/RibbonCMS

time_line:
  - text: "**お知らせ** RibbonCMS 開発開始"
    date: 2022年6月
  - text: "**リリース** 最初のバージョンが完成"
    date: 2022年7月
  - text: "**リリース** [RibbonCMS](https://ribboncms.github.io) のHPを公開"
    date: 2023年2月
  - text: "**リリース** 新しいフロントエンドテンプレート [FunctionalBlogTemplate](https://ribboncms.github.io/FunctionalBlogTemplate-DEMO) をリリース"
    date: 2023年2月
  - text: "**お知らせ** 開発環境整備＆ドキュメント化開始"
    date: 2023年7月
  - text: "**リリース** 新しいフロントエンドテンプレート [VanillaTemplate](https://ribboncms.github.io/VanillaTemplate-DEMO) をリリース"
    date: 2023年8月
```
